[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lightning-wandb"
authors = [{name = "SGpirr", email = "hooy9765@naver.com"}]
dynamic = ["version", "description"]
